error: Truncate long database exception messages
This is to avoid excessively long log entries, which can be
generated, for example, with MySQL, if a PNG image is included
in a query which fails.  Implicit exception context is suppressed
for Python 3 in case the cause exception also generates a large
log entry.